# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='opponents',
        ),
        migrations.AddField(
            model_name='player',
            name='opponents',
            field=models.ManyToManyField(to='tournament_api.Player'),
        ),
    ]
