# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_api', '0004_auto_20170902_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(blank=True, choices=[('WHITE', 'WHITE'), ('BLACK', 'BLACK'), ('DRAW', 'DRAW'), ('UNDETERMINED', 'Undetermined')], max_length=20, null=True),
        ),
    ]
