# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_api', '0006_auto_20170902_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(blank=True, choices=[('White', 'White won'), ('Black', 'Black won'), ('Draw', 'Match Drawn'), ('Undetermined', 'Undetermined')], default='Undetermined', max_length=20),
        ),
    ]
