# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_api', '0007_auto_20170902_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament_api.Round'),
        ),
    ]
