# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_api', '0008_auto_20170903_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='round',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament_api.Round'),
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together=set([('tournament', 'round_num')]),
        ),
    ]
