# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_api', '0010_auto_20170905_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='concluded',
            field=models.BooleanField(default=False),
        ),
    ]
