# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_api', '0011_round_concluded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(blank=True, choices=[('white', 'White won'), ('black', 'Black won'), ('draw', 'Match Drawn'), ('undetermined', 'Undetermined')], default='undetermined', max_length=20),
        ),
    ]
